# Generated by Django 4.2.5 on 2023-09-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='color',
            field=models.CharField(default='#00ac51', max_length=100),
        ),
    ]
