# Generated by Django 4.2.5 on 2023-09-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_content_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(upload_to='content_images/'),
        ),
    ]
